### 1. Encadenamiento de Excepciones

El encadenamiento de excepciones ocurre cuando una excepción no manejada dentro de una sección except tiene la excepción que se estaba manejando adjunta a ella.

**Ejemplo:**

```python
try:
    open("database.sqlite")
except OSError:
    raise RuntimeError("unable to handle error")
```

### 2. Sintaxis de raise con from

La cláusula from en la declaración raise indica que una excepción es consecuencia directa de otra.

**Ejemplo:**

```python
try:
    func()
except ConnectionError as exc:
    raise RuntimeError("Failed to open database") from exc
```

### 3. Deshabilitar el Encadenamiento Automático de Excepciones

Se puede deshabilitar el encadenamiento automático de excepciones usando from None.

**Ejemplo:**

```python
try:
    open('database.sqlite')
except OSError:
    raise RuntimeError from None
```
